graph LR
    Input((<a href="../src/main.cpp#L85" target="_blank" style="color:#e65100;text-decoration:none;">Камера</a>)) --> 
    Loader[<a href="../modules/perception.image_loader.simple.cppm" target="_blank" style="color:#4a90e2;text-decoration:none;">Image Loader</a>]
    Loader --> 
    Pre[<a href="../modules/perception.detector.simple.cppm" target="_blank" style="color:#4a90e2;text-decoration:none;">MockDetector</a>]
    Pre --> 
    Detect[<a href="../modules/perception.detector.simple.cppm" target="_blank" style="color:#4a90e2;text-decoration:none;">Detection</a>]
    Detect --> 
    Track[<a href="../modules/perception.detector.simple.cppm" target="_blank" style="color:#4a90e2;text-decoration:none;">Result</a>]
    Track --> 
    UI((<a href="../src/main.cpp#L120" target="_blank" style="color:#880e4f;text-decoration:none;">Визуализация</a>))
